### ISSUE TITLE
Admin: A distorted dashboard entries occurs upon clicking on one entry and mouse hover to the other.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Rainbow-Quartz#130]
![image](https://cloud.githubusercontent.com/assets/12791909/9708094/75d9dc12-5549-11e5-8f10-8d488c639879.png)

**Comment by Rahul-titan** [comment]
I cannot see any distorted dashboard entries in the admin section, could you please elaborate when exactly you are getting this issue.

**Comment by ermatitan** [comment]
Steps to replicate:
1. Click any option in the dashboard (banners, pages, plugins)
2. Then hover to any options in the dashboard. There you can see the clippings and overlapping of each entries. 

This maybe an issue with the current WP version since we can recreate this issue in all currently test sites.

**Comment by Rahul-titan** [comment]
I cannot see any distorted dashboard entries in the admin section. I tested it in all browsers but i didn't see it. Please advice.

**Comment by ermatitan** [comment]
As per Bernard conversation about this issue, this can be marked as Won't Fix since it's a Wordpress issue.
