### ISSUE TITLE
Sidebar gravity form field content where displayed on  ALL Caps.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Rainbow-Quartz#131]
![image](https://cloud.githubusercontent.com/assets/12791909/9708230/7732b2da-554b-11e5-8d42-c164efa44180.png)

**Comment by Rahul-titan** [comment]
As per design specification, font-family is Ostrich Sans Medium and its default style is in uppercase. If we want the text in lowercase then we should change the default font-family. Please advise.
