### ISSUE TITLE
Homepage: Start your project today form has no error message displayed after clicking submit button with incomplete form

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Rainbow-Quartz#21]
![image](https://cloud.githubusercontent.com/assets/12791909/9297092/53322788-44cc-11e5-9a21-89009e4fe678.png)

**Comment by Rahul-titan** [comment]
The pre-footer section height and start your project today form height are fixed. When we submit form the layout is getting misaligned. Therefore applied validation with red border to the fields as required field.

**Comment by ermatitan** [comment]
Hello Rahul, I undestand with the pre-footer height issue and error message should be in one line only but the grammar quiet not appropriate. Can you confirm with your lead what's the appropriate error message to be use. Thanks
